### ISSUE TITLE
A Brazilian serve

### ISSUE THREAD

**Issue by lucasprevidelli** [alexwathever/SocialBound-HTML5#17]
Hey man, how are you? I would like to set up a Brazilian server. Could you charge me a fee to configure a server? I have some money to invest. I am a traffic manager, and I believe I could build a good user base here. Is there a way to share your contact information? My email is [lucasprevidelli@gmail.com](mailto:lucasprevidelli@gmail.com).

**Comment by lucasprevidelli** [comment]
hello?

**Comment by Ox18** [comment]
@lucasprevidelli hi sir, pls, send a mail to xander.scorpio@gmail.com
